### ISSUE TITLE
problem with angular-ui-router

### ISSUE THREAD

**Issue by omarsedki** [shagstrom/angular-split-pane#1]
cannot add inside <split-pane-component >  ui-view

**Comment by dcjohnston** [comment]
Error: [$compile:multidir] Multiple directives [uiView, splitPaneComponent] asking for transclusion on: <div ui-view="mainView" data-split-pane-component="">.

Error: [$compile:multidir] Multiple directives [ngInclude, splitPaneComponent] asking for transclusion on: <div data-split-pane-component="" ng-include="'templates/_list-widget.html'">

Fixed by providing wrapper div's around the div's containing ng-include/ui-view directives, and placing the data-split-* directives on this wrapper parent.

**Comment by shagstrom** [comment]
@omarsedki works for me in Chrome, Safari and Firefox. Complete example here https://github.com/shagstrom/angular-split-pane-ui-route-example
